import { useLicenses } from "../hooks/useMarketplace";

export function MarketplaceLicensePage() {
  const { data } = useLicenses();
  if (!data) return null;

  return (
    <div className="space-y-6">
      <div>
        <p className="text-sm font-semibold uppercase tracking-wide text-slate-500">Licensing</p>
        <h1 className="mt-2 text-3xl font-semibold">NFT and product license registry</h1>
      </div>
      <div className="grid gap-4 lg:grid-cols-3">
        {data.licenses.map((license) => (
          <article key={license.id} className="rounded border border-slate-200 bg-white p-5 shadow-sm">
            <p className="text-sm font-semibold uppercase tracking-wide text-teal-700">{license.ownershipModel}</p>
            <h2 className="mt-2 text-xl font-semibold">{license.type}</h2>
            <dl className="mt-4 space-y-2 text-sm text-slate-600">
              <Row label="Transferable" value={license.transferable ? "yes" : "no"} />
              <Row label="Revokable" value={license.revokable ? "yes" : "no"} />
              <Row label="NFT bound" value={license.nftBound ? "yes" : "no"} />
              <Row label="Governance" value={license.governanceControlled ? "controlled" : "not controlled"} />
              <Row label="Expiration" value={license.expiration ?? "none"} />
            </dl>
            <div className="mt-4 flex flex-wrap gap-2">
              {license.permissions.map((permission) => (
                <span key={permission} className="rounded border border-slate-200 bg-slate-50 px-2 py-1 text-xs font-semibold text-slate-600">
                  {permission}
                </span>
              ))}
            </div>
          </article>
        ))}
      </div>
      <section className="rounded border border-slate-200 bg-white p-5 shadow-sm">
        <h2 className="text-xl font-semibold">Issued license runtime</h2>
        <p className="mt-2 text-sm text-slate-600">
          Persistent lifecycle records generated by purchase previews. No NFT transfer, settlement or live ownership validation is executed.
        </p>
        <div className="mt-4 overflow-x-auto">
          <table className="w-full min-w-[720px] text-left text-sm" aria-label="Issued license runtime records">
            <thead className="border-b border-slate-200 text-slate-500">
              <tr>
                <th className="py-2">License</th>
                <th>Product</th>
                <th>Holder</th>
                <th>State</th>
                <th>Expiration</th>
                <th>Restrictions</th>
              </tr>
            </thead>
            <tbody>
              {data.licenseRuntimes.length ? (
                data.licenseRuntimes.map((license) => (
                  <tr key={license.id} className="border-b border-slate-100">
                    <td className="py-3 font-medium">{license.licenseDefinitionId}</td>
                    <td>{data.products.find((product) => product.id === license.productId)?.title ?? license.productId}</td>
                    <td>{license.holder}</td>
                    <td>{license.state}</td>
                    <td>{license.expiresAt ?? "none"}</td>
                    <td>{license.governanceRestrictions.join(", ") || "none"}</td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan={6} className="py-4 text-slate-600">
                    No issued license runtime records yet. Use a buy-now preview to persist one.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </section>
    </div>
  );
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex justify-between gap-4">
      <dt>{label}</dt>
      <dd className="font-medium text-slate-900">{value}</dd>
    </div>
  );
}
